# Generated by Django 4.2 on 2023-04-21 18:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("turmas", "0002_matricula_turma_alunos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matricula",
            options={"ordering": ["turma", "data"]},
        ),
        migrations.AlterUniqueTogether(
            name="matricula",
            unique_together={("usuario", "turma")},
        ),
    ]
