# Generated by Django 4.2 on 2023-04-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modulos", "0003_auto_populando_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modulo",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
