# Generated by Django 4.2 on 2023-04-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modulos", "0005_aula"),
    ]

    operations = [
        migrations.AddField(
            model_name="aula",
            name="vimeo_id",
            field=models.CharField(default="1", max_length=32),
        ),
    ]
